apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portal-app
  template:
    metadata:
      name: portal-app
      labels:
        app: portal-app
    spec:
      containers:
        - name: portal-app-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
