apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: news-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-app
  serviceName: news-svc
  template:
    metadata:
      labels:
        app: news-app
      name: news-app
    spec:
      containers:
        - name: news-app-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: sistema-configmap
          volumeMounts:
            - name: images
              mountPath: /var/www/html/uploads
            - name: session
              mountPath: /tmp
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: images-pvc
        - name: session
          persistentVolumeClaim:
            claimName: session-pvc
